import type { Metadata } from "next";
import "./globals.css";
import ToastProvider from "@/components/ToastProvider";
import NextUIWrapper from "./NextUIWrapper";

export const metadata: Metadata = {
  title: "Task App",
  description: "Generated by GoDigital",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NextUIWrapper>
          <ToastProvider>
            <main className="container mx-auto h-screen flex items-center justify-center">
              {children}
            </main>
          </ToastProvider>
        </NextUIWrapper>
      </body>
    </html>
  );
}
